# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\christian\Documents\GitHub\triscan\gui\main.ui'
#
# Created: Mon Mar 10 21:26:54 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(300, 250)
        self.frame_6 = QtGui.QFrame(Form)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 280, 230))
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.status_lbl = QtGui.QLabel(self.frame_6)
        self.status_lbl.setGeometry(QtCore.QRect(10, 55, 186, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.status_lbl.setFont(font)
        self.status_lbl.setFrameShape(QtGui.QFrame.StyledPanel)
        self.status_lbl.setScaledContents(True)
        self.status_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.status_lbl.setWordWrap(False)
        self.status_lbl.setObjectName(_fromUtf8("status_lbl"))
        self.toolButton = QtGui.QToolButton(self.frame_6)
        self.toolButton.setGeometry(QtCore.QRect(50, 95, 36, 36))
        self.toolButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/48x48/png/48x48/System.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(24, 24))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.progressBar = QtGui.QProgressBar(self.frame_6)
        self.progressBar.setGeometry(QtCore.QRect(10, 200, 266, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.camBox = QtGui.QPushButton(self.frame_6)
        self.camBox.setGeometry(QtCore.QRect(130, 95, 36, 36))
        self.camBox.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/woofunction/woofunction-icons/camera_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.camBox.setIcon(icon1)
        self.camBox.setIconSize(QtCore.QSize(24, 24))
        self.camBox.setCheckable(True)
        self.camBox.setObjectName(_fromUtf8("camBox"))
        self.deg_lcd = QtGui.QLCDNumber(self.frame_6)
        self.deg_lcd.setGeometry(QtCore.QRect(200, 55, 61, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.deg_lcd.setFont(font)
        self.deg_lcd.setSmallDecimalPoint(False)
        self.deg_lcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.deg_lcd.setObjectName(_fromUtf8("deg_lcd"))
        self.label_2 = QtGui.QLabel(self.frame_6)
        self.label_2.setGeometry(QtCore.QRect(265, 55, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.rLaserBox = QtGui.QPushButton(self.frame_6)
        self.rLaserBox.setGeometry(QtCore.QRect(170, 95, 36, 36))
        self.rLaserBox.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/woofunction/woofunction-icons/arrow_right_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rLaserBox.setIcon(icon2)
        self.rLaserBox.setIconSize(QtCore.QSize(24, 24))
        self.rLaserBox.setCheckable(True)
        self.rLaserBox.setObjectName(_fromUtf8("rLaserBox"))
        self.lLaserBox = QtGui.QPushButton(self.frame_6)
        self.lLaserBox.setGeometry(QtCore.QRect(90, 95, 36, 36))
        self.lLaserBox.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/woofunction/woofunction-icons/arrow_left_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lLaserBox.setIcon(icon3)
        self.lLaserBox.setIconSize(QtCore.QSize(24, 24))
        self.lLaserBox.setCheckable(True)
        self.lLaserBox.setObjectName(_fromUtf8("lLaserBox"))
        self.frame_7 = QtGui.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 281, 46))
        self.frame_7.setFrameShape(QtGui.QFrame.Box)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.scanButton = QtGui.QCommandLinkButton(self.frame_7)
        self.scanButton.setGeometry(QtCore.QRect(185, 2, 96, 41))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/glossy_2_48x48/png_2/48x48/Steering wheel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/48x48/png/48x48/Stop.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.scanButton.setIcon(icon4)
        self.scanButton.setIconSize(QtCore.QSize(24, 24))
        self.scanButton.setCheckable(True)
        self.scanButton.setChecked(False)
        self.scanButton.setAutoRepeatDelay(3000)
        self.scanButton.setAutoDefault(False)
        self.scanButton.setObjectName(_fromUtf8("scanButton"))
        self.stepButton = QtGui.QCommandLinkButton(self.frame_7)
        self.stepButton.setGeometry(QtCore.QRect(0, 2, 91, 41))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/48x48/png/48x48/Forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stepButton.setIcon(icon5)
        self.stepButton.setIconSize(QtCore.QSize(24, 24))
        self.stepButton.setObjectName(_fromUtf8("stepButton"))
        self.turnButton = QtGui.QCommandLinkButton(self.frame_7)
        self.turnButton.setGeometry(QtCore.QRect(90, 2, 96, 41))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/48x48/png/48x48/Repeat.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.turnButton.setIcon(icon6)
        self.turnButton.setIconSize(QtCore.QSize(24, 24))
        self.turnButton.setObjectName(_fromUtf8("turnButton"))
        self.execButton = QtGui.QPushButton(self.frame_6)
        self.execButton.setGeometry(QtCore.QRect(10, 95, 36, 36))
        self.execButton.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/woofunction/woofunction-icons/search_chart_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.execButton.setIcon(icon7)
        self.execButton.setIconSize(QtCore.QSize(24, 24))
        self.execButton.setCheckable(False)
        self.execButton.setObjectName(_fromUtf8("execButton"))
        self.lightBox = QtGui.QPushButton(self.frame_6)
        self.lightBox.setGeometry(QtCore.QRect(210, 95, 36, 36))
        self.lightBox.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/woofunction/woofunction-icons/lightbulb_off_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/woofunction/woofunction-icons/lightbulb_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.lightBox.setIcon(icon8)
        self.lightBox.setIconSize(QtCore.QSize(24, 24))
        self.lightBox.setCheckable(True)
        self.lightBox.setObjectName(_fromUtf8("lightBox"))
        self.frame = QtGui.QFrame(self.frame_6)
        self.frame.setGeometry(QtCore.QRect(10, 140, 171, 51))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.scnmdlbl = QtGui.QLabel(self.frame)
        self.scnmdlbl.setGeometry(QtCore.QRect(60, 30, 61, 16))
        self.scnmdlbl.setObjectName(_fromUtf8("scnmdlbl"))
        self.lft_rd_btn = QtGui.QRadioButton(self.frame)
        self.lft_rd_btn.setGeometry(QtCore.QRect(10, 10, 51, 17))
        self.lft_rd_btn.setChecked(False)
        self.lft_rd_btn.setObjectName(_fromUtf8("lft_rd_btn"))
        self.rgt_rd_btn = QtGui.QRadioButton(self.frame)
        self.rgt_rd_btn.setGeometry(QtCore.QRect(60, 10, 51, 17))
        self.rgt_rd_btn.setObjectName(_fromUtf8("rgt_rd_btn"))
        self.dual_rd_btn = QtGui.QRadioButton(self.frame)
        self.dual_rd_btn.setGeometry(QtCore.QRect(120, 10, 51, 17))
        self.dual_rd_btn.setChecked(True)
        self.dual_rd_btn.setObjectName(_fromUtf8("dual_rd_btn"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Δ▲Δ Triscan", None))
        Form.setToolTip(_translate("Form", "options", None))
        self.status_lbl.setToolTip(_translate("Form", "what´s up?", None))
        self.status_lbl.setText(_translate("Form", "ready for rumble!", None))
        self.toolButton.setToolTip(_translate("Form", "options menue", None))
        self.camBox.setToolTip(_translate("Form", "Webcam toggle", None))
        self.deg_lcd.setToolTip(_translate("Form", "degrees", None))
        self.label_2.setText(_translate("Form", "°", None))
        self.rLaserBox.setToolTip(_translate("Form", "switch right laser on/off", None))
        self.lLaserBox.setToolTip(_translate("Form", "switch left laser on/off", None))
        self.scanButton.setToolTip(_translate("Form", "start/stop the scan", None))
        self.scanButton.setText(_translate("Form", "Scan", None))
        self.stepButton.setToolTip(_translate("Form", "one step move", None))
        self.stepButton.setText(_translate("Form", "Step", None))
        self.turnButton.setToolTip(_translate("Form", "turn the table", None))
        self.turnButton.setText(_translate("Form", "Turn", None))
        self.execButton.setToolTip(_translate("Form", "open the last scan file in the standard program for this filetype", None))
        self.lightBox.setToolTip(_translate("Form", "switch light on/off", None))
        self.scnmdlbl.setText(_translate("Form", "Scanmode", None))
        self.lft_rd_btn.setToolTip(_translate("Form", "single left scanmode", None))
        self.lft_rd_btn.setText(_translate("Form", "Left", None))
        self.rgt_rd_btn.setToolTip(_translate("Form", "single right scanmode", None))
        self.rgt_rd_btn.setText(_translate("Form", "Right", None))
        self.dual_rd_btn.setToolTip(_translate("Form", "dual scanmode", None))
        self.dual_rd_btn.setText(_translate("Form", "Dual", None))

import resources_rc
